Repository Rama-Moon/HonestHouse-Prototype, pull requests merged in 2025-09, with the labels that each got.

#5 [#4] Chore: 프로젝트 초기 폴더링 세팅
  HonestHouse-Prototype/HonestHouse-Prototype/Resources/c1.swift
  HonestHouse-Prototype/HonestHouse-Prototype/Sources/App/HonestHouse_PrototypeApp.swift
  HonestHouse-Prototype/HonestHouse-Prototype/Sources/Common/Enum/c2.swift
  HonestHouse-Prototype/HonestHouse-Prototype/Sources/Common/Extension/c3.swift
  HonestHouse-Prototype/HonestHouse-Prototype/Sources/Common/Protocol/c4.swift
  HonestHouse-Prototype/HonestHouse-Prototype/Sources/Core/Navigation/c5.swift
  HonestHouse-Prototype/HonestHouse-Prototype/Sources/Core/Util/Constants.swift
  HonestHouse-Prototype/HonestHouse-Prototype/Sources/Models/c7.swift
  HonestHouse-Prototype/HonestHouse-Prototype/Sources/Presentation/Case/Case.swift
  HonestHouse-Prototype/HonestHouse-Prototype/Sources/Presentation/Case/CaseSelectView.swift
  HonestHouse-Prototype/HonestHouse-Prototype/Sources/Presentation/Case/CustomActiveButton.swift
  HonestHouse-Prototype/HonestHouse-Prototype/Sources/Presentation/Case/RadioButton.swift
  HonestHouse-Prototype/HonestHouse-Prototype/Sources/Presentation/Case/RadioButtonGroup.swift
  HonestHouse-Prototype/HonestHouse-Prototype/Sources/Presentation/UIComponents/c8.swift
Labels: 📂 Chore

#8 Feat/#1
  HonestHouse-Prototype/HonestHouse-Prototype.xcodeproj/project.pbxproj
  HonestHouse-Prototype/HonestHouse-Prototype/ExposureMeterRepresentable.swift
  HonestHouse-Prototype/HonestHouse-Prototype/ExposureMeterUIView.swift
  HonestHouse-Prototype/HonestHouse-Prototype/ExposureMeterView.swift
  HonestHouse-Prototype/HonestHouse-Prototype/Info.plist
  HonestHouse-Prototype/HonestHouse-Prototype/Resources/Modifier/ValueChipModifier.swift
  HonestHouse-Prototype/HonestHouse-Prototype/Sources/Models/c7.swift
  HonestHouse-Prototype/HonestHouse-Prototype/Sources/Presentation/ExposureMeter/CameraManufacturerView.swift
  HonestHouse-Prototype/HonestHouse-Prototype/Sources/Presentation/ExposureMeter/ExposureMeterRepresentable.swift
  HonestHouse-Prototype/HonestHouse-Prototype/Sources/Presentation/ExposureMeter/ExposureMeterUIView.swift
  HonestHouse-Prototype/HonestHouse-Prototype/Sources/Presentation/ExposureMeter/ExposureMeterView.swift
  HonestHouse-Prototype/HonestHouse-Prototype/Sources/Presentation/Onboarding/CameraManufacturerView.swift
Labels: ✨ Feature

#10 ✨ Feat: #3 CameraSelectionView 구현
  HonestHouse-Prototype/HonestHouse-Prototype/Sources/Common/Enum/CameraItemSelectionType.swift
  HonestHouse-Prototype/HonestHouse-Prototype/Sources/Common/Enum/Manufacturer.swift
  HonestHouse-Prototype/HonestHouse-Prototype/Sources/Common/Enum/c2.swift
  HonestHouse-Prototype/HonestHouse-Prototype/Sources/Core/Util/Constants.swift
  HonestHouse-Prototype/HonestHouse-Prototype/Sources/Models/CameraBody.swift
  HonestHouse-Prototype/HonestHouse-Prototype/Sources/Models/CameraLens.swift
  HonestHouse-Prototype/HonestHouse-Prototype/Sources/Models/CanonItems.swift
  HonestHouse-Prototype/HonestHouse-Prototype/Sources/Models/NikonItems.swift
  HonestHouse-Prototype/HonestHouse-Prototype/Sources/Models/SonyItems.swift
  HonestHouse-Prototype/HonestHouse-Prototype/Sources/Presentation/Onboarding/CameraBodySelectionView.swift
  HonestHouse-Prototype/HonestHouse-Prototype/Sources/Presentation/Onboarding/CameraItemListView.swift
  HonestHouse-Prototype/HonestHouse-Prototype/Sources/Presentation/Onboarding/CameraLensSelectionView.swift
Labels: ✨ Feature

#13 [#11] Fix: CaseSelectView 디자인 수정 및 컴포넌트 Enum 재폴더링
  HonestHouse-Prototype/HonestHouse-Prototype/ContentView.swift
  HonestHouse-Prototype/HonestHouse-Prototype/Resources/c1.swift
  HonestHouse-Prototype/HonestHouse-Prototype/Sources/App/HonestHouse_PrototypeApp.swift
  HonestHouse-Prototype/HonestHouse-Prototype/Sources/Common/Enum/Case.swift
  HonestHouse-Prototype/HonestHouse-Prototype/Sources/Presentation/Case/CaseSelectView.swift
  HonestHouse-Prototype/HonestHouse-Prototype/Sources/Presentation/Case/RadioButton.swift
  HonestHouse-Prototype/HonestHouse-Prototype/Sources/Presentation/Case/RadioButtonGroup.swift
  HonestHouse-Prototype/HonestHouse-Prototype/Sources/Presentation/UIComponents/CustomActiveButton.swift
  HonestHouse-Prototype/HonestHouse-Prototype/Sources/Presentation/UIComponents/c8.swift
Labels: 🔨 Fix, 📂 Chore
