Repository Rama-Moon/HonestHouse-Prototype, pull requests merged in 2025-10, with the labels that each got.

#25 ✨ Feat: #16 태양 방위각, 고도 계산 로직 구현 및 SolarRotationView 구현
  HonestHouse-Prototype/HonestHouse-Prototype.xcodeproj/project.pbxproj
  HonestHouse-Prototype/HonestHouse-Prototype/Assets.xcassets/backlitGuide.imageset/Contents.json
  HonestHouse-Prototype/HonestHouse-Prototype/Assets.xcassets/backlitGuide.imageset/backlitGuide.pdf
  HonestHouse-Prototype/HonestHouse-Prototype/Assets.xcassets/sun.imageset/Contents.json
  HonestHouse-Prototype/HonestHouse-Prototype/Assets.xcassets/sun.imageset/sun.pdf
  HonestHouse-Prototype/HonestHouse-Prototype/Sources/Common/Enum/SunStatus.swift
  HonestHouse-Prototype/HonestHouse-Prototype/Sources/Core/Services/HeadingManager.swift
  HonestHouse-Prototype/HonestHouse-Prototype/Sources/Core/Services/LocationProvider.swift
  HonestHouse-Prototype/HonestHouse-Prototype/Sources/Core/Services/SolarManager.swift
  HonestHouse-Prototype/HonestHouse-Prototype/Sources/Presentation/ExposureMeter/SolarPostion/SolarRotationView.swift
Labels: ✨ Feature

#28 🔨 Fix: #24 추천 모드와 3요소 스펙트럼 분기 로직 수정
  HonestHouse-Prototype/HonestHouse-Prototype/Sources/Common/Enum/ModeSubtype.swift
  HonestHouse-Prototype/HonestHouse-Prototype/Sources/Core/Services/ExposureManager.swift
  HonestHouse-Prototype/HonestHouse-Prototype/Sources/Core/Util/SpectrumUtils.swift
  HonestHouse-Prototype/HonestHouse-Prototype/Sources/Models/Camera/CameraLens.swift
  HonestHouse-Prototype/HonestHouse-Prototype/Sources/Models/Exposure/ModeStrategy/A/A1Strategy.swift
  HonestHouse-Prototype/HonestHouse-Prototype/Sources/Models/Exposure/ModeStrategy/A/A2Strategy.swift
  HonestHouse-Prototype/HonestHouse-Prototype/Sources/Models/Exposure/ModeStrategy/A/A3Strategy.swift
  HonestHouse-Prototype/HonestHouse-Prototype/Sources/Models/Exposure/ModeStrategy/M/M1Strategy.swift
  HonestHouse-Prototype/HonestHouse-Prototype/Sources/Models/Exposure/ModeStrategy/M/M2Strategy.swift
  HonestHouse-Prototype/HonestHouse-Prototype/Sources/Models/Exposure/ModeStrategy/S/SStrategy.swift
  HonestHouse-Prototype/HonestHouse-Prototype/Sources/Presentation/Onboarding/CameraManufacturerView.swift
Labels: 🔨 Fix, ♻️ Refactor

#30 🔨 Fix: #29 잠금 버튼 눌렀을 때 EV값 및 카메라 프리뷰 멈추지 않는 문제
  HonestHouse-Prototype/HonestHouse-Prototype/Sources/Presentation/ExposureMeter/ExposureMeterRepresentable.swift
  HonestHouse-Prototype/HonestHouse-Prototype/Sources/Presentation/ExposureMeter/ExposureMeterUIView.swift
  HonestHouse-Prototype/HonestHouse-Prototype/Sources/Presentation/ExposureMeter/ExposureMeterView.swift
Labels: 🔨 Fix

#32 🔨 Fix: #24 추천 모드와 3요소 스펙트럼 분기 로직 수정
  HonestHouse-Prototype/HonestHouse-Prototype/Sources/Common/Protocol/ModeStrategy.swift
  HonestHouse-Prototype/HonestHouse-Prototype/Sources/Core/Services/ExposureManager.swift
  HonestHouse-Prototype/HonestHouse-Prototype/Sources/Core/Util/BaseValueUtils.swift
  HonestHouse-Prototype/HonestHouse-Prototype/Sources/Core/Util/SpectrumUtils.swift
  HonestHouse-Prototype/HonestHouse-Prototype/Sources/Models/Exposure/ModeStrategy/A/A1Strategy.swift
  HonestHouse-Prototype/HonestHouse-Prototype/Sources/Models/Exposure/ModeStrategy/A/A2Strategy.swift
  HonestHouse-Prototype/HonestHouse-Prototype/Sources/Models/Exposure/ModeStrategy/A/A3Strategy.swift
  HonestHouse-Prototype/HonestHouse-Prototype/Sources/Models/Exposure/ModeStrategy/M/M1Strategy.swift
  HonestHouse-Prototype/HonestHouse-Prototype/Sources/Models/Exposure/ModeStrategy/M/M2Strategy.swift
  HonestHouse-Prototype/HonestHouse-Prototype/Sources/Models/Exposure/ModeStrategy/S/SStrategy.swift
Labels: 🔨 Fix, ✨ Feature

#33 ✨ Feat: #31 추천 모드, 3요소 스펙트럼과 ExposureMeterView 연결하기
  HonestHouse-Prototype/HonestHouse-Prototype.xcodeproj/project.pbxproj
  HonestHouse-Prototype/HonestHouse-Prototype/Info.plist
  HonestHouse-Prototype/HonestHouse-Prototype/Sources/Common/Enum/CameraMode.swift
  HonestHouse-Prototype/HonestHouse-Prototype/Sources/Common/Enum/Guiding.swift
  HonestHouse-Prototype/HonestHouse-Prototype/Sources/Core/Services/ExposureManager.swift
  HonestHouse-Prototype/HonestHouse-Prototype/Sources/Models/OpenAPI/APIError.swift
  HonestHouse-Prototype/HonestHouse-Prototype/Sources/Models/OpenAPI/ChatMessage.swift
  HonestHouse-Prototype/HonestHouse-Prototype/Sources/Models/OpenAPI/ChatRequest.swift
  HonestHouse-Prototype/HonestHouse-Prototype/Sources/Models/OpenAPI/ChatResponse.swift
  HonestHouse-Prototype/HonestHouse-Prototype/Sources/Network/OpenAIService.swift
  HonestHouse-Prototype/HonestHouse-Prototype/Sources/Presentation/ExposureMeter/ExposureDetailView.swift
  HonestHouse-Prototype/HonestHouse-Prototype/Sources/Presentation/ExposureMeter/ExposureMeterView.swift
Labels: ✨ Feature

#40 ✨ Fix: #39 측광 로직에서 Race Condition 에러 수정
  HonestHouse-Prototype/HonestHouse-Prototype/Sources/Presentation/ExposureMeter/ExposureDetailView.swift
  HonestHouse-Prototype/HonestHouse-Prototype/Sources/Presentation/ExposureMeter/ExposureMeterUIView.swift
  HonestHouse-Prototype/HonestHouse-Prototype/Sources/Presentation/ExposureMeter/ExposureMeterView.swift
Labels: 🔨 Fix
